name: Test Installation

on: [workflow_dispatch, push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - 3.8
          
    name: Check installation with python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Update pip
      run: pip install --upgrade pip

    - name: Install package
      run: python -m pip install -e .[test]
